list(APPEND deps resource slang spirv-cross)
if(system MATCHES "linux")
    list(APPEND deps vulkan)
    list(APPEND features vulkan)
elseif(system MATCHES "darwin")
    list(APPEND features metal)
endif()
