list(APPEND deps slang spirv-cross)
if(${system} STREQUAL "linux")
    list(APPEND deps vulkan)
    list(APPEND features vulkan)
elseif(${system} STREQUAL "darwin")
    list(APPEND deps metal)
    list(APPEND features metal)
endif()
