file(GLOB core-libs RELATIVE ${TSSSNI_LIB_DIR} ${TSSSNI_LIB_DIR}/*)
foreach (lib ${core-libs})
  if (NOT IS_DIRECTORY ${TSSSNI_LIB_DIR}/${lib})
    list(REMOVE_ITEM core-libs ${lib})
  endif()
endforeach()
set_property(TARGET tsssni.src.core APPEND PROPERTY tsssni-link-libs ${core-libs})

file(GLOB core-srcs RELATIVE ${TSSSNI_SRC_DIR} ${TSSSNI_SRC_DIR}/*)
list(REMOVE_ITEM core-srcs core)
foreach (src ${core-srcs})
  if (NOT IS_DIRECTORY ${TSSSNI_SRC_DIR}/${src})
    list(REMOVE_ITEM core-srcs ${src})
  endif()
endforeach()
set_property(TARGET tsssni.src.core APPEND PROPERTY tsssni-link-srcs ${core-srcs})
