function(metatron_classify path mode)
  message(STATUS "processing ${mode}...")
  if (IS_DIRECTORY ${path})
    file(GLOB units RELATIVE ${path} ${path}/*)
    set(build-units)

    foreach(unit ${units})
      if(IS_DIRECTORY ${path}/${unit})
        list(APPEND build-units ${unit})
        metatron_evaluate(${unit} ${path}/${unit} ${mode})
      endif()
    endforeach()

    get_property(metatron-units TARGET metatron-build PROPERTY metatron-units)
    list(APPEND metatron-units ${build-units})
    set_property(TARGET metatron-build PROPERTY metatron-units ${metatron-units})
  endif()
endfunction()
