function(unite units)
    get_property(metatron-units TARGET metatron-build PROPERTY metatron-units)
    list(APPEND metatron-units ${units})
    set_property(TARGET metatron-build PROPERTY metatron-units ${metatron-units})
endfunction()

function(extend ext)
    find_package(${ext} REQUIRED)
    get_property(metatron-exts TARGET metatron-build PROPERTY metatron-exts)
    list(APPEND metatron-exts ${ext})
    set_property(TARGET metatron-build PROPERTY metatron-exts ${metatron-exts})
endfunction()

function(modulo path)
    list(APPEND CMAKE_MODULE_PATH ${path})
    set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} PARENT_SCOPE)
    file(GLOB mods ${path}/Find*.cmake)

    get_property(metatron-mods TARGET metatron-build PROPERTY metatron-mods)
    list(APPEND metatron-mods ${mods})
    set_property(TARGET metatron-build PROPERTY metatron-mods ${metatron-mods})
endfunction()

function(evaluate unit path mode)
    get_property(system TARGET metatron-build PROPERTY metatron-system)
    get_property(arch TARGET metatron-build PROPERTY metatron-arch)
    set(target metatron-${unit})
    set(setup ${path}/setup.cmake)
    set(deps)
    set(features)
    set(access)

    if(${mode} STREQUAL "src")
        if(EXISTS ${setup})
            include(${setup})
        endif()
        file(GLOB_RECURSE base ${path}/source/*.cpp)
        target_sources(metatron PRIVATE ${base})
        foreach(feature ${features})
            file(GLOB_RECURSE extra ${path}/source-${feature}/*.cpp)
            target_sources(metatron PRIVATE ${extra})
        endforeach()

        set(libs)
        foreach(dep ${deps})
            list(APPEND libs metatron-${dep})
        endforeach()
        if(libs)
            message(STATUS "metatron-${unit} link libraries ${deps}")
            target_link_libraries(metatron PUBLIC ${libs})
        endif()
        return()
    elseif(${mode} STREQUAL "ext")
        if(EXISTS ${path}/src)
            message(STATUS "build independent ${target}")
            add_library(${target} SHARED)
            set(mode "lib")
            set(access PUBLIC)
        else()
            message(STATUS "build external ${target}")
            add_library(${target} INTERFACE)
            set(access INTERFACE)
        endif()
        include(${setup})
    elseif(${mode} STREQUAL "bin")
        message(STATUS "build binary ${target}")
        add_executable(${target})
        set(access PUBLIC)
        file(GLOB_RECURSE sources ${path}/source/*.cpp)
        target_sources(${target} PRIVATE ${sources})
        include(${setup})
    endif()

    set_property(TARGET ${target} PROPERTY metatron-deps ${deps})
    set_property(TARGET ${target} PROPERTY metatron-path ${path})
    set_property(TARGET ${target} PROPERTY metatron-mode ${mode})
    set_property(TARGET ${target} PROPERTY metatron-access ${access})
endfunction()

function(solve path mode)
    message(STATUS "processing ${mode}...")
    if(NOT IS_DIRECTORY ${path})
        return()
    endif()

    file(GLOB units RELATIVE ${path} ${path}/*)
    set(build-units)
    foreach(unit ${units})
        if(IS_DIRECTORY ${path}/${unit})
            list(APPEND build-units ${unit})
            evaluate(${unit} ${path}/${unit} ${mode})
        endif()
    endforeach()
    unite("${build-units}")
endfunction()

function(collect)
    message(STATUS "build combined metatron")
    add_library(metatron SHARED)
    target_include_directories(metatron INTERFACE $<INSTALL_INTERFACE:include>)
    solve(${CMAKE_CURRENT_LIST_DIR}/ext "ext")
    solve(${CMAKE_CURRENT_LIST_DIR}/src "src")
    solve(${CMAKE_CURRENT_LIST_DIR}/bin "bin")
endfunction()
