function(link unit)
    set(target metatron-${unit})
    get_property(deps TARGET ${target} PROPERTY metatron-deps)
    get_property(mode TARGET ${target} PROPERTY metatron-mode)
    get_property(access TARGET ${target} PROPERTY metatron-access)

    set(libs)
    foreach(dep ${deps})
        if(${mode} STREQUAL "ext")
            list(APPEND libs ${dep})
        elseif(${dep} STREQUAL "metatron")
            list(APPEND libs metatron)
        else()
            list(APPEND libs metatron-${dep})
        endif()
    endforeach()

    if(libs)
        message(STATUS "${target} link libraries ${deps}")
        target_link_libraries(${target} ${access} ${libs})
    endif()
endfunction()

function(connect)
    get_property(metatron-units TARGET metatron-build PROPERTY metatron-units)
    foreach(unit ${metatron-units})
        if(TARGET metatron-${unit})
            link(${unit})
        endif()
    endforeach()
endfunction()
