function(predefine)
    set_property(TARGET metatron-build PROPERTY metatron-prefix ${CMAKE_INSTALL_PREFIX})
    add_compile_definitions(MTT_PREFIX="${CMAKE_INSTALL_PREFIX}")

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set_property(TARGET metatron-build PROPERTY metatron-system "linux")
        add_compile_definitions(MTT_SYSTEM_LINUX)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set_property(TARGET metatron-build PROPERTY metatron-system "darwin")
        add_compile_definitions(MTT_SYSTEM_DARWIN)
    else()
        message(FATAL_ERROR "system ${CMAKE_SYSTEM_NAME} not supported")
    endif()
    get_property(system TARGET metatron-build PROPERTY metatron-system)

    if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|AMD64")
        set_property(TARGET metatron-build PROPERTY metatron-arch "x86_64")
        add_compile_definitions(MTT_ARCH_X86_64)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
        set_property(TARGET metatron-build PROPERTY metatron-arch "aarch64")
    else()
        message(FATAL_ERROR "arch ${CMAKE_SYSTEM_PROCESSOR} not supported")
        add_compile_definitions(MTT_ARCH_AARCH64)
    endif()
    get_property(arch TARGET metatron-build PROPERTY metatron-arch)
endfunction()

function(prepare)
    define_property(TARGET PROPERTY metatron-units)
    define_property(TARGET PROPERTY metatron-exts)
    define_property(TARGET PROPERTY metatron-mods)

    define_property(TARGET PROPERTY metatron-deps)
    define_property(TARGET PROPERTY metatron-path)
    define_property(TARGET PROPERTY metatron-mode)
    define_property(TARGET PROPERTY metatron-access)

    define_property(TARGET PROPERTY metatron-system)
    define_property(TARGET PROPERTY metatron-arch)
    define_property(TARGET PROPERTY metatron-prefix)

    add_library(metatron-build INTERFACE)
    predefine()
endfunction()
